export const experienceData = [
    {
        title: "Frontend Developer",
        companyName: "MacHelp NYC",
        icon: '/experience/machelp.webp',
        date: "2023 - present",
        points: [
            "Implemented new solutions and features within current projects.",
            "Provided assistance in existing projects.",
            "Conducted performance optimization.",
            "Enhanced cross-browser compatibility.",
            "Collaborated on UI/UX design.",
        ],
    },
    {
        title: "Fullstack Developer / Owner",
        companyName: "eRZet",
        icon: '/experience/erzet.webp',
        date: "2022 - present",
        points: [
            "Developed and maintained web applications with Next.js.",
            "Created and optimized websites using modern web technologies.",
            "Implemented CI/CD Pipelines.",
            "Developed a Role-Playing Game from scratch.",
            "Enhanced User Experience.",
        ],
    },
    {
        title: "Frontend Developer",
        companyName: "Aurora Creation",
        icon: '/experience/aurora.webp',
        date: "2022 - present",
        points: [
            "Managed and implemented new e-commerce projects.",
            "Led a development team.",
            "Facilitated the onboarding of new employees.",
            "Conducted code reviews and provided mentorship.",
            "Provided support in existing projects.",
            "Communicated directly with clients.",
        ],
    },
    {
        title: "Frontend Developer",
        companyName: "Freelancing",
        icon: '/experience/coding.svg',
        date: "2021 - present",
        points: [
            "Developed custom web applications.",
            "Full project lifecycle management.",
            "SEO optimization.",
            "Content Management System integration.",
            "Troubleshooting and support.",
        ],
    },
];
